# netlify.toml

[build]
  publish = "."

[functions]
  directory = "functions"
  node_bundler = "esbuild"

  [functions.node_version18]
    external_node_modules = ["web-push", "resend"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200